<a href="https://colab.research.google.com/github/Fahrisetiadarma/DataAnalytics/blob/main/SleepQuality.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [ ]:
import pandas as pd
from openpyxl import load_workbook
df = pd.read_csv('/content/gdrive/MyDrive/Dataset.csv')
df

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [ ]:
df.dtypes

Person ID                    int64
Gender                      object
Age                          int64
Occupation                  object
Sleep Duration             float64
Quality of Sleep             int64
Physical Activity Level      int64
Stress Level                 int64
BMI Category                object
Blood Pressure              object
Heart Rate                   int64
Daily Steps                  int64
Sleep Disorder              object
dtype: object

In [ ]:
df.isna().sum()

Person ID                  0
Gender                     0
Age                        0
Occupation                 0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Blood Pressure             0
Heart Rate                 0
Daily Steps                0
Sleep Disorder             0
dtype: int64

In [ ]:
df.columns = ['No','JK','umur','pekerjaan','durasitidur','kualitastidur','levelaktivitas','levelstress','bmi','tekanandarah','detakjantung','steps','kelainan']

In [ ]:
df.loc[:,['JK','umur','pekerjaan','durasitidur','levelaktivitas','bmi','levelstress','kelainan']]

,JK,umur,pekerjaan,durasitidur,levelaktivitas,bmi,levelstress,kelainan
0,Male,27,Software Engineer,6.1,42,Overweight,6,None
1,Male,28,Doctor,6.2,60,Normal,8,None
2,Male,28,Doctor,6.2,60,Normal,8,None
3,Male,28,Sales Representative,5.9,30,Obese,8,Sleep Apnea
4,Male,28,Sales Representative,5.9,30,Obese,8,Sleep Apnea
...,...,...,...,...,...,...,...,...
369,Female,59,Nurse,8.1,75,Overweight,3,Sleep Apnea
370,Female,59,Nurse,8.0,75,Overweight,3,Sleep Apnea
371,Female,59,Nurse,8.1,75,Overweight,3,Sleep Apnea
372,Female,59,Nurse,8.1,75,Overweight,3,Sleep Apnea
373,Female,59,Nurse,8.1,75,Overweight,3,Sleep Apnea

In [ ]:
df.head()

,No,JK,umur,pekerjaan,durasitidur,kualitastidur,levelaktivitas,levelstress,bmi,tekanandarah,detakjantung,steps,kelainan
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [ ]:
d_train = df[['JK','umur','pekerjaan','durasitidur','levelaktivitas','bmi','detakjantung','levelstress','kelainan']].reset_index(drop=True)
d_train

,JK,umur,pekerjaan,durasitidur,levelaktivitas,bmi,detakjantung,levelstress,kelainan
0,Male,27,Software Engineer,6.1,42,Overweight,77,6,None
1,Male,28,Doctor,6.2,60,Normal,75,8,None
2,Male,28,Doctor,6.2,60,Normal,75,8,None
3,Male,28,Sales Representative,5.9,30,Obese,85,8,Sleep Apnea
4,Male,28,Sales Representative,5.9,30,Obese,85,8,Sleep Apnea
...,...,...,...,...,...,...,...,...,...
369,Female,59,Nurse,8.1,75,Overweight,68,3,Sleep Apnea
370,Female,59,Nurse,8.0,75,Overweight,68,3,Sleep Apnea
371,Female,59,Nurse,8.1,75,Overweight,68,3,Sleep Apnea
372,Female,59,Nurse,8.1,75,Overweight,68,3,Sleep Apnea
373,Female,59,Nurse,8.1,75,Overweight,68,3,Sleep Apnea

In [ ]:
selected_columns = d_train[['bmi', 'kelainan']]
print(selected_columns)

            bmi     kelainan
0    Overweight         None
1        Normal         None
2        Normal         None
3         Obese  Sleep Apnea
4         Obese  Sleep Apnea
..          ...          ...
369  Overweight  Sleep Apnea
370  Overweight  Sleep Apnea
371  Overweight  Sleep Apnea
372  Overweight  Sleep Apnea
373  Overweight  Sleep Apnea

[374 rows x 2 columns]

In [ ]:
import sys
from itertools import chain, combinations
from collections import defaultdict
from optparse import OptionParser
from operator import mul

In [ ]:
def subsets(arr):
    """ Returns non empty subsets of arr"""
    return chain(*[combinations(arr, i + 1) for i, a in enumerate(arr)])

def returnItemsWithMinSupport(itemSet, transactionList, minSupport, freqSet):
        """calculates the support for items in the itemSet and returns a subset
       of the itemSet each of whose elements satisfies the minimum support"""
        _itemSet = set()
        localSet = defaultdict(int)

        for item in itemSet:
                for transaction in transactionList:
                        if item.issubset(transaction):
                                freqSet[item] += 1
                                localSet[item] += 1

        for item, count in localSet.items():
                support = float(count)/len(transactionList)

                if support >= minSupport:
                        _itemSet.add(item)

        return _itemSet
def joinSet(itemSet, length):
        """Join a set with itself and returns the n-element itemsets"""
        return set([i.union(j) for i in itemSet for j in itemSet if len(i.union(j)) == length])

def getItemSetTransactionList(data_iterator):
    transactionList = list()
    itemSet = set()
    for record in data_iterator:
        transaction = frozenset(record)
        transactionList.append(transaction)
        for item in transaction:
            itemSet.add(frozenset([item]))              # Generate 1-itemSets
    return itemSet, transactionList

def runApriori(data_iter, minSupport, minConfidence):
    """
    run the apriori algorithm. data_iter is a record iterator
    Return both:
     - items (tuple, support)
     - rules ((pretuple, posttuple), confidence)
    """
    itemSet, transactionList = getItemSetTransactionList(data_iter)

    freqSet = defaultdict(int)
    largeSet = dict()
    # Global dictionary which stores (key=n-itemSets,value=support)
    # which satisfy minSupport

    assocRules = dict()
    # Dictionary which stores Association Rules

    oneCSet = returnItemsWithMinSupport(itemSet,
                                        transactionList,
                                        minSupport,
                                        freqSet)

    currentLSet = oneCSet
    k = 2
    while(currentLSet != set([])):
        largeSet[k-1] = currentLSet
        currentLSet = joinSet(currentLSet, k)
        currentCSet = returnItemsWithMinSupport(currentLSet,
                                                transactionList,
                                                minSupport,
                                                freqSet)
        currentLSet = currentCSet
        k = k + 1

    def getSupport(item):
            """local function which Returns the support of an item"""
            return float(freqSet[item])/len(transactionList)

    toRetItems = []
    for key, value in largeSet.items():
        toRetItems.extend([(tuple(item), getSupport(item))
                           for item in value])

    toRetRules = []
    for key, value in largeSet.items():
        for item in value:
            _subsets = map(frozenset, [x for x in subsets(item)])
            for element in _subsets:
                remain = item.difference(element)
                if len(remain) > 0:
                    confidence = getSupport(item)/getSupport(element)
                    if confidence >= minConfidence:
                        toRetRules.append(((tuple(element), tuple(remain)),
                                           confidence))
    return toRetItems, toRetRules

import operator
def printResults(items, rules):
    for item, support in sorted(items, key=operator.itemgetter(1)):
        print("item: %s , %.3f" % (str(item), support))
    print("\n------------------------ RULES:")
    for rule, confidence in sorted(rules, key=operator.itemgetter(1)):
        pre, post = rule
        print("Rule: %s ==> %s , %.3f" % (str(pre), str(post), confidence))

def getSupportAimplikasiB(A, B):
    rule = list(A)
    dict_support = B
    result = 0
    for index_dict_support in dict_support:
        list_index_dict_support = list(index_dict_support)
        check = []
        for data_index in list_index_dict_support:
            if data_index in rule and len(list_index_dict_support) >= len(rule):
                check.append(True)
            else:
                check.append(False)
        if(reduce(mul, check, 1)==True):
#             print(list_index_dict_support)
#             print(dict_support[index_dict_support])
            result = dict_support[index_dict_support]

    return result

def dataFromFile(fname):
        """Function which reads from the file and yields a generator"""
        file_iter = open(fname, 'rU')
        for line in file_iter:
                line = line.strip().rstrip(',')                         # Remove trailing comma
                record = frozenset(line.split(','))
                yield record

In [ ]:
list_data = []

for index, data in d_train.iterrows():
    temp_data = []
    temp_data.append(data['bmi'])
    temp_data.append(data['kelainan'])
    list_data.append(temp_data)

In [ ]:
minSupport = 0.1
minConfidence = 0.5

items, rules = runApriori(list_data, minSupport, minConfidence)
printResults(items, rules)

item: ('Insomnia', 'Overweight') , 0.171
item: ('Sleep Apnea', 'Overweight') , 0.174
item: ('Insomnia',) , 0.206
item: ('Sleep Apnea',) , 0.209
item: ('Overweight',) , 0.396
item: ('None', 'Normal') , 0.489
item: ('Normal',) , 0.521
item: ('None',) , 0.586

------------------------ RULES:
Rule: ('Insomnia',) ==> ('Overweight',) , 0.831
Rule: ('Sleep Apnea',) ==> ('Overweight',) , 0.833
Rule: ('None',) ==> ('Normal',) , 0.836
Rule: ('Normal',) ==> ('None',) , 0.938